package il.cshaifasweng.hsts.entities.enums;

public enum MessageType {
    LOGIN_REQUEST,
    LOGIN_RESPONSE,
    LOGOUT_REQUEST,
    LOGOUT_RESPONSE,

    GET_TEACHER_COURSES_REQUEST,
    GET_TEACHER_COURSES_RESPONSE,

    GET_COURSE_QUESTIONS_REQUEST,
    GET_COURSE_QUESTIONS_RESPONSE,

    CREATE_QUESTION_REQUEST,
    CREATE_QUESTION_RESPONSE,
    UPDATE_QUESTION_REQUEST,
    UPDATE_QUESTION_RESPONSE,
    DELETE_QUESTION_REQUEST,
    DELETE_QUESTION_RESPONSE,

    CREATE_EXAM_REQUEST,
    CREATE_EXAM_RESPONSE,

    GET_PENDING_EXAMS_REQUEST,
    GET_PENDING_EXAMS_RESPONSE,
    APPROVE_EXAM_REQUEST,
    APPROVE_EXAM_RESPONSE,
    REJECT_EXAM_REQUEST,
    REJECT_EXAM_RESPONSE,

    GET_APPROVED_EXAMS_REQUEST,
    GET_APPROVED_EXAMS_RESPONSE,
    SCHEDULE_EXAM_REQUEST,
    SCHEDULE_EXAM_RESPONSE,
    GET_TEACHER_EXAM_INSTANCES_REQUEST,
    GET_TEACHER_EXAM_INSTANCES_RESPONSE,
    EXTEND_EXAM_DURATION_REQUEST,
    EXTEND_EXAM_DURATION_RESPONSE,
    EXAM_DURATION_EXTENDED_NOTIFICATION,

    START_EXAM_REQUEST,
    START_EXAM_RESPONSE,
    SUBMIT_EXAM_REQUEST,
    SUBMIT_EXAM_RESPONSE,
    TIMEOUT_EXAM_REQUEST,
    TIMEOUT_EXAM_RESPONSE,

    GET_SUBMISSIONS_FOR_REVIEW_REQUEST,
    GET_SUBMISSIONS_FOR_REVIEW_RESPONSE,
    APPROVE_SUBMISSION_REQUEST,
    APPROVE_SUBMISSION_RESPONSE,

    GET_STUDENT_RESULTS_REQUEST,
    GET_STUDENT_RESULTS_RESPONSE,

    GET_TEACHER_STATISTICS_REQUEST,
    GET_TEACHER_STATISTICS_RESPONSE,

    ERROR
}
